(define (square x) (* x x))
(define (average x y)
  (/ (+ x y) 2))

(define (sqrt-iter guess x)
  (define improved (improve guess x))
  (if (good-enough? improved guess)
      improved
      (sqrt-iter improved x)))
(define (improve guess x)
  (average guess (/ x guess)))
(define (good-enough? improved guess)
  (< (abs (- 1.0 (/ improved guess))) 0.001))
(define (my-sqrt x)
  (sqrt-iter 1.0 x))
